name: Slack Notifications

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    

jobs:
  notifySlack:

    runs-on: ubuntu-latest

    steps:
    - name: Notify slack
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      uses: pullreminders/slack-action@master
      with:
        args: '{\"channel\":\"C02T44Z00AG\",\"blocks\":[{\"type\":\"section\",\"text\":{\"type\":\"mrkdwn\",\"text\":\"You have a new pull request,{\"type\":\"section\","\fields\": [{\"type\":\"mrkdwn\",\"text\":\"*Title:*\n${{ github.event.pull_request.title }}"},{\"type\":\"mrkdwn\",\"text\":\"*By:*\n${{ github.event.pull_request.user.login }}"},{\"type\":\"mrkdwn\",\"text\":\"*URL:*\n${{ github.event.pull_request.html_url }}"},{\"type\":\"mrkdwn\",\"text\":\"*Action:*\n${{ github.event.pull_request.action }}"},{\"type\":\"mrkdwn\",\"text\":\"*Request State:*\n${{ github.event.pull_request.state }}"}}]}'
